/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StateStateCodeRouteImport } from './routes/state.$stateCode'
import { Route as CountryAlpha2RouteImport } from './routes/country.$alpha2'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateStateCodeRoute = StateStateCodeRouteImport.update({
  id: '/state/$stateCode',
  path: '/state/$stateCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryAlpha2Route = CountryAlpha2RouteImport.update({
  id: '/country/$alpha2',
  path: '/country/$alpha2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/country/$alpha2': typeof CountryAlpha2Route
  '/state/$stateCode': typeof StateStateCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/country/$alpha2': typeof CountryAlpha2Route
  '/state/$stateCode': typeof StateStateCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/country/$alpha2': typeof CountryAlpha2Route
  '/state/$stateCode': typeof StateStateCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/country/$alpha2' | '/state/$stateCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/country/$alpha2' | '/state/$stateCode'
  id: '__root__' | '/' | '/country/$alpha2' | '/state/$stateCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryAlpha2Route: typeof CountryAlpha2Route
  StateStateCodeRoute: typeof StateStateCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/$stateCode': {
      id: '/state/$stateCode'
      path: '/state/$stateCode'
      fullPath: '/state/$stateCode'
      preLoaderRoute: typeof StateStateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$alpha2': {
      id: '/country/$alpha2'
      path: '/country/$alpha2'
      fullPath: '/country/$alpha2'
      preLoaderRoute: typeof CountryAlpha2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryAlpha2Route: CountryAlpha2Route,
  StateStateCodeRoute: StateStateCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
